/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayZenRouteImport } from './routes/play.zen'
import { Route as PlayMultiplayerRouteImport } from './routes/play.multiplayer'
import { Route as PlayCasualRouteImport } from './routes/play.casual'
import { Route as PlayCampaignRouteImport } from './routes/play.campaign'
import { Route as PlayMultiplayerCodeRouteImport } from './routes/play.multiplayer.$code'

const TutorialRoute = TutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayZenRoute = PlayZenRouteImport.update({
  id: '/play/zen',
  path: '/play/zen',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayMultiplayerRoute = PlayMultiplayerRouteImport.update({
  id: '/play/multiplayer',
  path: '/play/multiplayer',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayCasualRoute = PlayCasualRouteImport.update({
  id: '/play/casual',
  path: '/play/casual',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayCampaignRoute = PlayCampaignRouteImport.update({
  id: '/play/campaign',
  path: '/play/campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayMultiplayerCodeRoute = PlayMultiplayerCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => PlayMultiplayerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tutorial': typeof TutorialRoute
  '/play/campaign': typeof PlayCampaignRoute
  '/play/casual': typeof PlayCasualRoute
  '/play/multiplayer': typeof PlayMultiplayerRouteWithChildren
  '/play/zen': typeof PlayZenRoute
  '/play/multiplayer/$code': typeof PlayMultiplayerCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tutorial': typeof TutorialRoute
  '/play/campaign': typeof PlayCampaignRoute
  '/play/casual': typeof PlayCasualRoute
  '/play/multiplayer': typeof PlayMultiplayerRouteWithChildren
  '/play/zen': typeof PlayZenRoute
  '/play/multiplayer/$code': typeof PlayMultiplayerCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tutorial': typeof TutorialRoute
  '/play/campaign': typeof PlayCampaignRoute
  '/play/casual': typeof PlayCasualRoute
  '/play/multiplayer': typeof PlayMultiplayerRouteWithChildren
  '/play/zen': typeof PlayZenRoute
  '/play/multiplayer/$code': typeof PlayMultiplayerCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/settings'
    | '/sitemap.xml'
    | '/tutorial'
    | '/play/campaign'
    | '/play/casual'
    | '/play/multiplayer'
    | '/play/zen'
    | '/play/multiplayer/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/settings'
    | '/sitemap.xml'
    | '/tutorial'
    | '/play/campaign'
    | '/play/casual'
    | '/play/multiplayer'
    | '/play/zen'
    | '/play/multiplayer/$code'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/settings'
    | '/sitemap.xml'
    | '/tutorial'
    | '/play/campaign'
    | '/play/casual'
    | '/play/multiplayer'
    | '/play/zen'
    | '/play/multiplayer/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TutorialRoute: typeof TutorialRoute
  PlayCampaignRoute: typeof PlayCampaignRoute
  PlayCasualRoute: typeof PlayCasualRoute
  PlayMultiplayerRoute: typeof PlayMultiplayerRouteWithChildren
  PlayZenRoute: typeof PlayZenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/zen': {
      id: '/play/zen'
      path: '/play/zen'
      fullPath: '/play/zen'
      preLoaderRoute: typeof PlayZenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/multiplayer': {
      id: '/play/multiplayer'
      path: '/play/multiplayer'
      fullPath: '/play/multiplayer'
      preLoaderRoute: typeof PlayMultiplayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/casual': {
      id: '/play/casual'
      path: '/play/casual'
      fullPath: '/play/casual'
      preLoaderRoute: typeof PlayCasualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/campaign': {
      id: '/play/campaign'
      path: '/play/campaign'
      fullPath: '/play/campaign'
      preLoaderRoute: typeof PlayCampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/multiplayer/$code': {
      id: '/play/multiplayer/$code'
      path: '/$code'
      fullPath: '/play/multiplayer/$code'
      preLoaderRoute: typeof PlayMultiplayerCodeRouteImport
      parentRoute: typeof PlayMultiplayerRoute
    }
  }
}

interface PlayMultiplayerRouteChildren {
  PlayMultiplayerCodeRoute: typeof PlayMultiplayerCodeRoute
}

const PlayMultiplayerRouteChildren: PlayMultiplayerRouteChildren = {
  PlayMultiplayerCodeRoute: PlayMultiplayerCodeRoute,
}

const PlayMultiplayerRouteWithChildren = PlayMultiplayerRoute._addFileChildren(
  PlayMultiplayerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TutorialRoute: TutorialRoute,
  PlayCampaignRoute: PlayCampaignRoute,
  PlayCasualRoute: PlayCasualRoute,
  PlayMultiplayerRoute: PlayMultiplayerRouteWithChildren,
  PlayZenRoute: PlayZenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
